# Generated by Django 5.2 on 2025-04-26 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(max_length=50)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_username', models.CharField(max_length=50, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_cree_par', models.CharField(blank=True, max_length=50, null=True)),
                ('user_cree_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_miseajour_par', models.CharField(blank=True, max_length=50, null=True)),
                ('user_miseajour_date', models.DateTimeField(auto_now=True)),
                ('user_role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('formation_id', models.AutoField(primary_key=True, serialize=False)),
                ('formation_titre', models.CharField(max_length=255)),
                ('formation_ref', models.CharField(max_length=50)),
                ('formation_niveau', models.CharField(max_length=50)),
                ('formation_description', models.TextField()),
                ('formation_cout', models.IntegerField()),
                ('formation_mise_a_jour_cree', models.CharField(blank=True, max_length=50, null=True)),
                ('formation_mise_a_jour_date', models.DateTimeField(auto_now=True)),
                ('formation_pays', models.CharField(max_length=50)),
                ('formation_duree', models.IntegerField()),
                ('formation_prerequis', models.CharField(blank=True, max_length=255, null=True)),
                ('formation_programme', models.TextField(blank=True, null=True)),
                ('formation_cible', models.TextField(blank=True, null=True)),
                ('formation_objectif', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_debut_date', models.DateTimeField()),
                ('session_fin_date', models.DateTimeField()),
                ('session_cree_par', models.CharField(blank=True, max_length=50, null=True)),
                ('session_cree_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.formation')),
                ('participants', models.ManyToManyField(related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('structure_id', models.AutoField(primary_key=True, serialize=False)),
                ('structure_varchar', models.CharField(max_length=255)),
                ('structure_code', models.CharField(max_length=50)),
                ('structure_cree_par', models.CharField(blank=True, max_length=50, null=True)),
                ('structure_cree_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('structure_miseajour_par', models.CharField(blank=True, max_length=50, null=True)),
                ('structure_miseajour_date', models.DateTimeField(auto_now=True)),
                ('structure_niveau', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_name='structures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFormation',
            fields=[
                ('user_formation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('state_formation', models.CharField(max_length=50)),
                ('valide_par', models.CharField(blank=True, max_length=50, null=True)),
                ('valide_date', models.DateTimeField(blank=True, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_formations', to='users.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_formations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
